apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herringbone
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: quay.io/herringbone/detectionengine-matcher
    newTag: a310d627
    digest: sha256:7e4f26b0554c9fd8ac963f7e47a5d2721f84a34bc32e1d2887b9a711084c5b75
