apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herringbone
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: quay.io/herringbone/detectionengine-matcher
    newTag: 8c01bde9
    digest: sha256:375ea388d534d639a71735e04a26df3198d3ccba2fa8b8397b293e939e3cceea
