apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herringbone
resources:
  - deployment.yaml
images:
  - name: quay.io/herringbone/enrichment
    newName: quay.io/herringbone/parser-enrichment
    newTag: b4a8a79c
    digest: sha256:e828b4a361024655bba8814add66c80d9494074fe3ddb9ad65912e7ab1c4757f
