apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herringbone
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: quay.io/herringbone/incidents-correlator
    newTag: d6fb2fcd
    digest: sha256:78c8518983128f15065f09961a982c1722467ba8117434a34f9eb66ce3a83640
