apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herringbone
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: quay.io/herringbone/incidents-correlator
    newTag: 8a838e6f
    digest: sha256:7d29cde13fe194cec3d5c0ed22872aa5615a76392916cf6b43671c21aa8617b6
