apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herringbone
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: quay.io/herringbone/incidents-correlator
    newTag: b4a8a79c
    digest: sha256:35dbeb29ec7ca02c6b9ff3392383b2bd7b0160fcb0a3285bf7125d32f88a0b74
