apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herringbone
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: quay.io/herringbone/parser-cardset
    newTag: 50da3b76
    digest: sha256:f53eccc3f5652e63486c52040efdba5e54d834f80c61056058400f9453b65e69
