services:
  detectionengine-matcher:
    container_name: detectionengine-matcher
    image: quay.io/herringbone/detectionengine-matcher:c956252f@sha256:757d4ff9870d79f401691521bf1a7dc418022d4090ebca0a000c3553146488d9
    restart: unless-stopped
    networks:
      - herringbone
    expose:
      - "7003"
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    secrets:
      - service_token
      - service_jwt_public_key
      - jwt_secret
secrets:
  service_token:
    file: ./secrets/runtime/detectionengine_matcher_service_token
  service_jwt_public_key:
    file: ./secrets/runtime/service_jwt_public_key
  jwt_secret:
    file: ./secrets/runtime/jwt_secret
networks:
  herringbone:
    external: true
    name: herringbone_net
