services:
  logingestion-receiver:
    container_name: logingestion-receiver
    image: quay.io/herringbone/receiver:c0b5e87b@sha256:0d03aa80bc7a764667c1892c09518722e70a2a67da08b75a9a0eb5df85deb1a2
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - herringbone
    ports:
      - "7004:7004"
      - "7004:7004/udp"
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      DB_NAME: ${DB_NAME}
      AUTH_DB: ${AUTH_DB}
      COLLECTION_NAME: "events"
      RECEIVER_TYPE: ${RECEIVER_TYPE}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
networks:
  herringbone:
    external: true
