services:
  incidents-orchestrator:
    container_name: incidents-orchestrator
    image: quay.io/herringbone/incidents-orchestrator:97cd747e@sha256:e376d6f3a69ad8bbf8748146107a3d2b5e2e3e7bf838f97ce761414ba9f31e81
    restart: unless-stopped
    networks:
      - herringbone
    expose:
      - "7013"
    environment:
      CORRELATOR_URL: "http://incidents-correlator:7012/incidents/correlator/correlate"
      INCIDENTSET_API: "http://incidents-incidentset:7011/incidents/incidentset"
      # Context
      HERRINGBONE_SERVICE: incidents-orchestrator
      HERRINGBONE_UNIT: incidents
      HERRINGBONE_ELEMENT: orchestrator
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    secrets:
      - service_token
      - service_jwt_public_key
      - jwt_secret
secrets:
  service_token:
    file: ./secrets/runtime/incidents_orchestrator_service_token
  service_jwt_public_key:
    file: ./secrets/runtime/service_jwt_public_key
  jwt_secret:
    file: ./secrets/runtime/jwt_secret
networks:
  herringbone:
    external: true
    name: herringbone_net
