services:
  operations-center:
    image: quay.io/herringbone/operations-center:sha-145e9062@sha256:e1564976bf26354f1ed30bacbcfb9c0627d40b82d98fa04cbf1dbc9e093a9932
    container_name: operations-center
    restart: unless-stopped

    profiles: ["ops"]

    networks:
      - herringbone

    expose:
      - "8080"

    read_only: true
    tmpfs:
      - /tmp
      - /var/lib/nginx/tmp
      - /run
    security_opt:
      - no-new-privileges:true
