services:
  herringbone-logs:
    image: quay.io/herringbone/herringbone-logs:fdd6e007@sha256:8abd8d1edf6936eb5cf0eb4a0473e8a703e7899d76445e9c7e908345f6b61bca
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - herringbone
    expose:
      - "7010"
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      DB_NAME: ${DB_NAME}
      AUTH_DB: ${AUTH_DB}
      COLLECTION_NAME: events
      HERRINGBONE_SERVICE: herringbone-logs
      HERRINGBONE_UNIT: herringbone
      HERRINGBONE_ELEMENT: logs
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    secrets:
      - jwt_secret
    deploy:
      replicas: ${HERRINGBONE_LOGS_REPLICAS:-3}
networks:
  herringbone:
    external: true
    name: herringbone_net
secrets:
  jwt_secret:
    file: ./secrets/runtime/jwt_secret
