services:
  operations-center:
    image: quay.io/herringbone/operations-center:15926a80@sha256:30b079d8c77f0fc07bc419601c67f1c087da373c9f56a16cb9b2ed8d0c20f9cf
    restart: unless-stopped
    profiles:
    - ops
    environment:
      HERRINGBONE_SERVICE: operations-center
      HERRINGBONE_UNIT: operations-center
      HERRINGBONE_ELEMENT: ui
    networks:
    - herringbone
    expose:
    - "8080"
    read_only: true
    tmpfs:
    - /tmp
    - /var/lib/nginx/tmp
    - /run
    security_opt:
    - no-new-privileges:true
    deploy:
      replicas: ${OPERATIONS_CENTER_REPLICAS:-3}
networks:
  herringbone:
    external: true
    name: herringbone_net
