services:
  parser-extractor:
    container_name: parser-extractor
    image: quay.io/herringbone/parser-extractor:febc6c1d@sha256:cecb2e3cadf98577e56d413effe5ae51d4b20dc22ede17277023415ca7594d66
    restart: unless-stopped
    networks:
      - herringbone
    expose:
      - "7006"
    working_dir: /app-root
    environment:
      PYTHONPATH: /app-root:/python-packages:/modules
      # Context
      HERRINGBONE_SERVICE: parser-extractor
      HERRINGBONE_UNIT: parser
      HERRINGBONE_ELEMENT: extractor
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    secrets:
      - service_jwt_public_key
networks:
  herringbone:
    external: true
    name: herringbone_net
secrets:
  service_jwt_public_key:
    file: ./secrets/runtime/service_jwt_public_key
