services:
  herringbone-logs:
    container_name: herringbone-logs
    image: quay.io/herringbone/herringbone-logs:f4aee25b@sha256:80f9e3cbbb100da51e9bf27e9db1bea90098e64c9fbc1a5631c15f1921bd01f4
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - herringbone
    expose:
      - "7010"
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      DB_NAME: ${DB_NAME}
      AUTH_DB: ${AUTH_DB}
      COLLECTION_NAME: events
      # Context
      HERRINGBONE_SERVICE: herringbone-logs
      HERRINGBONE_UNIT: herringbone
      HERRINGBONE_ELEMENT: logs
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    secrets:
      - jwt_secret
networks:
  herringbone:
    external: true
secrets:
  jwt_secret:
    file: ./secrets/runtime/jwt_secret
