services:
  herringbone-auth:
    container_name: herringbone-auth
    image: quay.io/herringbone/herringbone-auth:6d5efdcb@sha256:a5c155d98fc8fe9527072a80b8ba3ec92b1b77dc173f4b73c2975f70ed79d627
    user: "65532:65532"
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - herringbone
    expose:
      - "7001"
    environment:
      # Mongo
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      DB_NAME: ${DB_NAME}
      AUTH_DB: ${AUTH_DB}
      # Secrets files
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      SERVICE_JWT_PRIVATE_KEY_FILE: /run/secrets/service_jwt_private_key
      SERVICE_JWT_PUBLIC_KEY_FILE: /run/secrets/service_jwt_public_key
      # Bootstrap token
      BOOTSTRAP_TOKEN_FILE: /run/secrets/bootstrap_token
      # Context
      HERRINGBONE_SERVICE: herringbone-auth
      HERRINGBONE_UNIT: herringbone
      HERRINGBONE_ELEMENT: auth
    secrets:
      - jwt_secret
      - service_jwt_private_key
      - service_jwt_public_key
      - bootstrap_token
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
secrets:
  jwt_secret:
    file: ./secrets/runtime/jwt_secret
  service_jwt_private_key:
    file: ./secrets/runtime/service_jwt_private_key
  service_jwt_public_key:
    file: ./secrets/runtime/service_jwt_public_key
  bootstrap_token:
    file: ./secrets/runtime/bootstrap_token
