services:
  incidents-incidentset:
    container_name: incidents-incidentset
    image: quay.io/herringbone/incidents-incidentset:cec08f94@sha256:73c1f4ed4540da1780d7f44d29d819d5d6ece54dd4b6d96cdf05f70ca17e0e55
    restart: unless-stopped
    networks:
      - herringbone
    expose:
      - "7011"
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      DB_NAME: ${DB_NAME}
      AUTH_DB: ${AUTH_DB}
      COLLECTION_NAME: "incidents"
      # Context
      HERRINGBONE_SERVICE: incidents-incidentset
      HERRINGBONE_UNIT: incidents
      HERRINGBONE_ELEMENT: incidentset
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    secrets:
      - service_token
      - service_jwt_public_key
      - jwt_secret
secrets:
  service_token:
    file: ./secrets/runtime/incidents_incidentset_service_token
  service_jwt_public_key:
    file: ./secrets/runtime/service_jwt_public_key
  jwt_secret:
    file: ./secrets/runtime/jwt_secret
networks:
  herringbone:
    external: true
    name: herringbone_net
