services:
  incidents-correlator:
    container_name: incidents-correlator
    image: quay.io/herringbone/incidents-correlator:8a838e6f@sha256:7d29cde13fe194cec3d5c0ed22872aa5615a76392916cf6b43671c21aa8617b6
    restart: unless-stopped
    networks:
      - herringbone
    expose:
      - "7012"
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      DB_NAME: ${DB_NAME}
      AUTH_DB: ${AUTH_DB}
      COLLECTION_NAME: "incidents"
      EVENTS_API_BASE: "http://herringbone-logs:7010/herringbone/logs/events"
      # Context
      HERRINGBONE_SERVICE: incidents-correlator
      HERRINGBONE_UNIT: incidents
      HERRINGBONE_ELEMENT: correlator
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    secrets:
      - service_token
      - service_jwt_public_key
      - jwt_secret
secrets:
  service_token:
    file: ./secrets/runtime/incidents_correlator_service_token
  service_jwt_public_key:
    file: ./secrets/runtime/service_jwt_public_key
  jwt_secret:
    file: ./secrets/runtime/jwt_secret
networks:
  herringbone:
    external: true
    name: herringbone_net
