services:
  detectionengine-matcher:
    container_name: detectionengine-matcher
    image: quay.io/herringbone/detectionengine-matcher:33f1a898@sha256:8fe6fe74c03693f9386c4c53e86c4bb51c8f62bf850787859bc33a94935227b9
    restart: unless-stopped
    networks:
      - herringbone
    expose:
      - "7003"
    environment:
      # Context
      HERRINGBONE_SERVICE: detectionengine-matcher
      HERRINGBONE_UNIT: detectionengine
      HERRINGBONE_ELEMENT: matcher
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    secrets:
      - service_token
      - service_jwt_public_key
      - jwt_secret
secrets:
  service_token:
    file: ./secrets/runtime/detectionengine_matcher_service_token
  service_jwt_public_key:
    file: ./secrets/runtime/service_jwt_public_key
  jwt_secret:
    file: ./secrets/runtime/jwt_secret
networks:
  herringbone:
    external: true
    name: herringbone_net
