services:
  detectionengine-matcher:
    image: quay.io/herringbone/detectionengine-matcher:5fba37db@sha256:ad4a100a70a43953616ec7e257b1117ac604fbb8ebc0bf7bf8688b0f626e640c
    restart: unless-stopped
    networks:
      - herringbone
    expose:
      - "7003"
    environment:
      HERRINGBONE_SERVICE: detectionengine-matcher
      HERRINGBONE_UNIT: detectionengine
      HERRINGBONE_ELEMENT: matcher
      MATCHER_DEBUG: ${MATCHER_DEBUG:-false}
      MATCHER_REGEX_CACHE_SIZE: ${MATCHER_REGEX_CACHE_SIZE:-4096}
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    secrets:
      - service_token
      - service_jwt_public_key
      - jwt_secret
    deploy:
      replicas: ${DETECTIONENGINE_MATCHER_REPLICAS:-3}
secrets:
  service_token:
    file: ./secrets/runtime/detectionengine_matcher_service_token
  service_jwt_public_key:
    file: ./secrets/runtime/service_jwt_public_key
  jwt_secret:
    file: ./secrets/runtime/jwt_secret
networks:
  herringbone:
    external: true
    name: herringbone_net
