services:
  herringbone-logs:
    container_name: herringbone-logs
    image: quay.io/herringbone/herringbone-logs:5b72b9c1@sha256:f4129285efb0bbdd668d222ba9db667abb9787ee571275686f39ebb0684ac1c1
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - herringbone
    expose:
      - "7010"
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      DB_NAME: ${DB_NAME}
      AUTH_DB: ${AUTH_DB}
      COLLECTION_NAME: events
      # Context
      HERRINGBONE_SERVICE: herringbone-logs
      HERRINGBONE_UNIT: herringbone
      HERRINGBONE_ELEMENT: logs
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    secrets:
      - jwt_secret
networks:
  herringbone:
    external: true
secrets:
  jwt_secret:
    file: ./secrets/runtime/jwt_secret
