services:
  logingestion-receiver:
    container_name: logingestion-receiver
    image: quay.io/herringbone/receiver:a6ea709b@sha256:a92b9a01b94aa4dbd1d26acf3775acc03fc47b28cfccdf5897df4c8b01d43858
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - herringbone
    ports:
      - "7004:7004"
      - "7004:7004/udp"
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      DB_NAME: ${DB_NAME}
      AUTH_DB: ${AUTH_DB}
      COLLECTION_NAME: "events"
      RECEIVER_TYPE: ${RECEIVER_TYPE}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
networks:
  herringbone:
    external: true
