services:
  detectionengine-ruleset:
    container_name: detectionengine-ruleset
    image: quay.io/herringbone/detectionengine-ruleset:50da3b76@sha256:58f4010bb1731013ef5c55c8dd414812182bdaa285756bb7e5d7feb194d327a3
    restart: unless-stopped
    networks:
      - herringbone
    expose:
      - "7002"
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      DB_NAME: ${DB_NAME}
      AUTH_DB: ${AUTH_DB}
      COLLECTION_NAME: "rules"
      # Context
      HERRINGBONE_SERVICE: detectionengine-ruleset
      HERRINGBONE_UNIT: detectionengine
      HERRINGBONE_ELEMENT: ruleset
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    secrets:
      - service_token
      - service_jwt_public_key
      - jwt_secret
secrets:
  service_token:
    file: ./secrets/runtime/detectionengine_ruleset_service_token
  service_jwt_public_key:
    file: ./secrets/runtime/service_jwt_public_key
  jwt_secret:
    file: ./secrets/runtime/jwt_secret
networks:
  herringbone:
    external: true
    name: herringbone_net
