services:
  parser-extractor:
    container_name: parser-extractor
    image: quay.io/herringbone/parser-extractor:0e98c8bc@sha256:b31d7239b4d1c2c9bae0699fa5619a00b093f09d02f06677156d8cb7e19a7f9d
    restart: unless-stopped
    networks:
      - herringbone
    expose:
      - "7006"
    working_dir: /app-root
    environment:
      PYTHONPATH: /app-root:/python-packages:/modules
      # Context
      HERRINGBONE_SERVICE: parser-extractor
      HERRINGBONE_UNIT: parser
      HERRINGBONE_ELEMENT: extractor
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    secrets:
      - service_jwt_public_key
networks:
  herringbone:
    external: true
    name: herringbone_net
secrets:
  service_jwt_public_key:
    file: ./secrets/runtime/service_jwt_public_key
