services:
  herringbone-search:
    image: quay.io/herringbone/herringbone-search:b4a8a79c@sha256:30b1eeb364f0a715ed298bb73ca4969b7543361ffc7c1e4d8978e2fb8048207e
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - herringbone
    expose:
      - "7014"
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      DB_NAME: ${DB_NAME}
      AUTH_DB: ${AUTH_DB}
      HERRINGBONE_SERVICE: herringbone-search
      HERRINGBONE_UNIT: herringbone
      HERRINGBONE_ELEMENT: search
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    secrets:
      - jwt_secret
    deploy:
      replicas: ${HERRINGBONE_SEARCH_REPLICAS:-3}
networks:
  herringbone:
    external: true
    name: herringbone_net
secrets:
  jwt_secret:
    file: ./secrets/runtime/jwt_secret
