services:
  herringbone-search:
    container_name: herringbone-search
    image: quay.io/herringbone/herringbone-search:50da3b76@sha256:c4aacb920ec69727ec70c82f88a6aad802aead0d7056c2174f11c2ae9d610504
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - herringbone
    expose:
      - "7014"
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      DB_NAME: ${DB_NAME}
      AUTH_DB: ${AUTH_DB}
      # Context
      HERRINGBONE_SERVICE: herringbone-search
      HERRINGBONE_UNIT: herringbone
      HERRINGBONE_ELEMENT: search
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    secrets:
      - jwt_secret
networks:
  herringbone:
    external: true
secrets:
  jwt_secret:
    file: ./secrets/runtime/jwt_secret
