services:
  incidents-incidentset:
    image: quay.io/herringbone/incidents-incidentset:b4a8a79c@sha256:94632e19ab15ba6b2e249a6fa04272bea703c61a1add8830cb9e59faa7f06809
    restart: unless-stopped
    networks:
      - herringbone
    expose:
      - "7011"
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      DB_NAME: ${DB_NAME}
      AUTH_DB: ${AUTH_DB}
      COLLECTION_NAME: incidents
      HERRINGBONE_SERVICE: incidents-incidentset
      HERRINGBONE_UNIT: incidents
      HERRINGBONE_ELEMENT: incidentset
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    secrets:
      - service_token
      - service_jwt_public_key
      - jwt_secret
    deploy:
      replicas: ${INCIDENTS_INCIDENTSET_REPLICAS:-3}
secrets:
  service_token:
    file: ./secrets/runtime/incidents_incidentset_service_token
  service_jwt_public_key:
    file: ./secrets/runtime/service_jwt_public_key
  jwt_secret:
    file: ./secrets/runtime/jwt_secret
networks:
  herringbone:
    external: true
    name: herringbone_net
