services:
  operations-center:
    image: quay.io/herringbone/operations-center:0520ac4a@sha256:8343fd75a5a624f7a7958f1752d050e22f7a3e7fad2a31e83b9150683abec8b9
    restart: unless-stopped
    profiles:
    - ops
    environment:
      HERRINGBONE_SERVICE: operations-center
      HERRINGBONE_UNIT: operations-center
      HERRINGBONE_ELEMENT: ui
    networks:
    - herringbone
    expose:
    - "8080"
    read_only: true
    tmpfs:
    - /tmp
    - /var/lib/nginx/tmp
    - /run
    security_opt:
    - no-new-privileges:true
    deploy:
      replicas: ${OPERATIONS_CENTER_REPLICAS:-3}
networks:
  herringbone:
    external: true
    name: herringbone_net
