events {}

http {
  resolver 127.0.0.11 valid=10s;

  server {
    listen 80;

    set $ops     http://operations-center:8080;
    set $auth    http://herringbone-auth:7001;
    set $logs    http://herringbone-logs:7010;
    set $search  http://herringbone-search:7014;
    set $parser  http://parser-cardset:7005;
    set $extract http://parser-extractor:7006;
    set $match   http://detectionengine-matcher:7003;
    set $rules   http://detectionengine-ruleset:7002;
    set $corr    http://incidents-correlator:7012;
    set $orc     http://incidents-orchestrator:7013;
    set $incset  http://incidents-incidentset:7011;

    location = / {
      return 200 "Herringbone Proxy Online\n";
    }

    location /herringbone/auth/ {
      proxy_pass $auth;
    }

    location /herringbone/logs/ {
      proxy_pass $logs;
    }

    location /herringbone/search/ {
      proxy_pass $search;
    }

    location /parser/cardset/ {
      proxy_pass $parser;
    }

    location /parser/extractor/ {
      proxy_pass $extract;
    }

    location /detectionengine/matcher/ {
      proxy_pass $match;
    }

    location /detectionengine/ruleset/ {
      proxy_pass $rules;
    }

    location /incidents/correlator/ {
      proxy_pass $corr;
    }

    location /incidents/orchestrator/ {
      proxy_pass $orc;
    }

    location /incidents/incidentset/ {
      proxy_pass $incset;
    }

    location / {
      proxy_pass $ops;
    }
  }
}