apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herringbone
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: quay.io/herringbone/detectionengine-ruleset
    newTag: 666e6917
    digest: sha256:c5967383ccdf88f2affeb85820329d20fe39acd6f3686c1a93491a3d3da91dd3
