apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herringbone
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: quay.io/herringbone/parser-extractor
    newTag: 837fbfb4
    digest: sha256:9fe5f1899c2b04818cf0a8e14aee48b6c83a08900a39e436f3aeca1ce2b8a5c8
