apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herringbone
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: quay.io/herringbone/parser-extractor
    newTag: 3e85b495
    digest: sha256:27b071f82e3357f1570f75838af24555a0fa7ebb3ed3f446f718deaee315188b
