apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herringbone
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: quay.io/herringbone/parser-extractor
    newTag: 0c03b59f
    digest: sha256:d6c77ecd8fee4a09cc8f580530052e547515ca6ba8c33f105de62ec2ca4626f4
