apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herringbone
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: quay.io/herringbone/herringbone-auth
    newTag: b4a8a79c
    digest: sha256:a20fbba76ab5471a3b545e9e49c3a4860428aeb8eea0d8bf8ad4e3085fd901a5
