services:
  detectionengine-matcher:
    container_name: detectionengine-matcher

    build:
      context: ../../..
      dockerfile: detectionengine/matcher/docker/Dockerfile

    restart: unless-stopped

    ports:
      - "7003:7003"

    env_file:
      - .env
