apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herringbone
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: quay.io/herringbone/incidents-incidentset
    newTag: f19a6a50
    digest: sha256:76eb66bf889735e256a744eaa3894938dc47961e6582bfd09e92da19bcf3f40e
