apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herringbone
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: quay.io/herringbone/incidents-incidentset
    newTag: f93162d0
    digest: sha256:eb71a1b8fdbda7073fa7bd97df19b89f6c5aee8adba5602af177e557a8739dcf
