apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herringbone
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: quay.io/herringbone/incidents-incidentset
    newTag: 04a0959d
    digest: sha256:38278e65cf6073cc14b63602e94c620f23db596bc227a78f1a52e2c49b5fba2f
