apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herringbone
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: quay.io/herringbone/incidents-orchestrator
    newTag: 50da3b76
    digest: sha256:e363ff7a4783820d9e87ad7bfd47229902c603bc1f425e5b49cd1ff387dad6a7
