apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herringbone
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: quay.io/herringbone/incidents-orchestrator
    newTag: 8867b3d2
    digest: sha256:c04a26354585520ee653533a0b6e7470e217240a78ea412adcff7083de2d57dd
