apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herringbone
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: quay.io/herringbone/incidents-orchestrator
    newTag: 97cd747e
    digest: sha256:e376d6f3a69ad8bbf8748146107a3d2b5e2e3e7bf838f97ce761414ba9f31e81
