from jsonschema import validate, ValidationError


class CardSchema:
    """Validates JSON data for a parse card entry.

    The schema intentionally allows a little flexibility because cards can be
    authored by the UI, imported from packs, or generated by automation. Runtime
    matching logic decides the selector semantics.
    """

    def __init__(self):
        selector_schema = {
            "type": "object",
            "additionalProperties": True,
            "properties": {
                "type": {"type": "string"},
                "value": {"anyOf": [{"type": "string"}, {"type": "number"}, {"type": "boolean"}, {"type": "null"}]},
                "path": {"type": "string"},
                "field": {"type": "string"},
                "match": {
                    "type": "string",
                    "enum": ["exact", "contains", "regex", "exists", "not_exists"],
                },
            },
            "required": ["type"],
        }

        negative_selector_schema = {
            "type": "object",
            "additionalProperties": True,
            "properties": {
                "type": {"type": "string"},
                "value": {"anyOf": [{"type": "string"}, {"type": "number"}, {"type": "boolean"}, {"type": "null"}]},
                "path": {"type": "string"},
                "field": {"type": "string"},
                "match": {
                    "type": "string",
                    "enum": ["exact", "contains", "regex", "exists", "not_exists"],
                },
            },
            "required": ["type"],
        }

        selector_schema["properties"].update({
            "not": {
                "anyOf": [
                    negative_selector_schema,
                    {"type": "array", "items": negative_selector_schema},
                ]
            },
            "and_not": {
                "anyOf": [
                    negative_selector_schema,
                    {"type": "array", "items": negative_selector_schema},
                ]
            },
            "exclude": {
                "anyOf": [
                    negative_selector_schema,
                    {"type": "array", "items": negative_selector_schema},
                ]
            },
            "excludes": {
                "anyOf": [
                    negative_selector_schema,
                    {"type": "array", "items": negative_selector_schema},
                ]
            },
        })

        self.schema = {
            "type": "object",
            "additionalProperties": True,
            "properties": {
                "name": {"type": "string"},
                "metadata": {
                    "type": "object",
                    "additionalProperties": True,
                    "properties": {
                        "folder": {"type": "string"},
                        "type": {"type": "string"},
                        "label": {"type": "string"},
                        "source": {"type": "string"},
                        "pack": {"type": "string"},
                        "tags": {
                            "type": "array",
                            "items": {"type": "string"},
                        },
                    },
                },
                "selector": selector_schema,
                "regex": {
                    "type": "array",
                    "items": {"type": "object", "additionalProperties": {"type": "string"}},
                },
                "jsonp": {
                    "type": "array",
                    "items": {"type": "object", "additionalProperties": {"type": "string"}},
                },
            },
            "required": ["selector"],
            "anyOf": [
                {"required": ["regex"]},
                {"required": ["jsonp"]},
            ],
        }

    def __call__(self, data: dict) -> dict:
        return self.validate(data)

    def validate(self, data: dict) -> dict:
        try:
            validate(instance=data, schema=self.schema)
            return {"valid": True, "error": None}
        except ValidationError as e:
            return {"valid": False, "error": e.message}
