apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herringbone
resources:
  - deployment.yaml
images:
  - name: quay.io/herringbone/detectionengine-detector
    newTag: f1b0a7f0
    digest: sha256:1943b12c23f417d723f5899d14676f67faf58fd94f58de8726af5d4a25237f6a
