apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herringbone
resources:
  - deployment.yaml
images:
  - name: quay.io/herringbone/detectionengine-detector
    newTag: 90103508
    digest: sha256:7b2c1fae1407c6527017c6e8e99f449f1f40ff7fba7891f6d20547a5c8fd20bf
