apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herringbone
resources:
  - deployment.yaml
images:
  - name: quay.io/herringbone/detectionengine-detector
    newTag: 8f0ea086
    digest: sha256:f65d2c2d293d7e659d0eff22c8720c2b8d8c2358747b60d2d8e327bb5620d710
