apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herringbone
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: quay.io/herringbone/receiver
    newTag: e54e8170
    digest: "sha256:3737a566772abbd91d55982463367f65f28ffcfb4be546e767a2ab78824cdc74"
