apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: herringbone
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: quay.io/herringbone/receiver
    newTag: 6faf333f
    digest: "sha256:e032bbb7924e7fc92017018605f78af03f8c4eaf995d720088d2a276e59e6177"
